### ISSUE TITLE
Does not work when using Ed25519 key on YubiKey: Agent admitted failure to sign using the key

### ISSUE THREAD

**Issue by Frederick888** [jbeverly/pam_ssh_agent_auth#28] opened 2020-09-23 12:09 UTC
I'm facing a similar issue to https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1762340.html

I created an Ed25519 Authentication subkey via GnuPG and enabled it for SSH in gpg-agent. Then after copying the public SSH key into the remote machine, I was then able to SSH and sudo using the PGP key flawlessly.

However, after transferring the key to YubiKey, I can still SSH into the remote machine but when I sudo I constantly got `pam_ssh_agent_auth: Agent admitted failure to sign using the key.` in logs. Unlike the Debian bug report linked above, it just kept failing in my case instead of randomly succeeds.

Then still using the same YubiKey, I created an RSA 4096 Authentication subkey and transferred it into the YubiKey, then pam_ssh_agent_auth started working again.

I'm running Arch Linux on both local and remote machines. Here's some relevant info about my setup:

pam_ssh_agent_auth version: 0.10.4-2
PAM: `auth          sufficient      pam_ssh_agent_auth.so file=~/.ssh/authorized_keys`
sudoers: Added `Defaults env_keep += "SSH_AUTH_SOCK"`
`~/.ssh/rc`:
```bash
if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
```

I've been using pam_ssh_agent_auth for quite some time so unless there's any additional configuration needed specially for Ed25519, I think the problem is unlikely to be caused by my setup. It's possible that this is somehow caused by YubiKey firmware or GnuPG, in which case I apologise for reporting it to the wrong place but it'd be great if you can shed some light on me to figure out whose responsibility it is.

**Comment by rfpronk** [comment] 2020-11-11 17:11
I'm experiencing the same issue.

Using a Yubikey with a RSA4096 key for years with this module. 
Now I'm trying to switch to a newer Yubikey with a ed25519 key.

The stock packages (0.10.3) didn't work so I compiled the master branch of this project and included #24 but still doesn't work.
Running that on Ubuntu 18.04, but also tried 20.04 and Debian Buster.

My client (MacOS Catalina) runs the latest gnupg from homebrew
```
➜  ~ gpg --version
gpg (GnuPG) 2.2.23
libgcrypt 1.8.7
```

My Yubikey 5C has firmware 5.26

I'm also not sure this project contains the error.  Things like ssh itself and gpg signing works without any problems so it does point towards it.

Sometimes it works, mostly it doesn't. There is no pattern in how often it does.
For example: (when it asks for my password I Ctrl-C out)
```
➜  ~ ssh server
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-45-generic x86_64)
No mail.
Last login: Wed Nov 11 18:04:19 2020 from 2001:....
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
[sudo] password for robin:
robin@server:~$ sudo echo "it works"
it works
```

On failures `/var/log/auth.log`
```
Nov 11 18:04:39 server sudo[15605]: pam_ssh_agent_auth: matching key found: file/command /etc/ssh/sudo_authorized_keys, line 1
Nov 11 18:04:39 server sudo[15605]: pam_ssh_agent_auth: Found matching ED25519 key: .....
Nov 11 18:04:39 server sudo[15605]: pam_ssh_agent_auth: Agent admitted failure to sign using the key.
Nov 11 18:04:39 server sudo[15605]: pam_ssh_agent_auth: Failed Authentication: `robin' as `robin' using /etc/ssh/sudo_authorized_keys
Nov 11 18:04:40 server sudo[15605]: pam_unix(sudo:auth): conversation failed
```

And on success
```
Nov 11 18:04:42 server sudo[15746]: pam_ssh_agent_auth: matching key found: file/command /etc/ssh/sudo_authorized_keys, line 1
Nov 11 18:04:42 server sudo[15746]: pam_ssh_agent_auth: Found matching ED25519 key: ....
Nov 11 18:04:46 server sudo[15746]: pam_ssh_agent_auth: Authenticated (agent): `robin' as `robin' using /etc/ssh/sudo_authorized_keys
```

From the client, debug logging to max , gpg agent debug log
```
2020-11-11 18:04:39 gpg-agent[68355] DBG: chan_9 <- OK
2020-11-11 18:04:39 gpg-agent[68355] DBG: chan_9 -> PKAUTH  OPENPGP.3
2020-11-11 18:04:39 gpg-agent[68355] DBG: chan_9 <- ERR 100663351 Invalid value <SCD>
2020-11-11 18:04:39 gpg-agent[68355] smartcard signing failed: Invalid value
2020-11-11 18:04:39 gpg-agent[68355] ssh sign request failed: Invalid value <SCD>
2020-11-11 18:04:39 gpg-agent[68355] ssh request handler for sign_request (13) ready
2020-11-11 18:04:39 gpg-agent[68355] DBG: chan_9 -> RESTART
2020-11-11 18:04:39 gpg-agent[68355] DBG: chan_9 <- OK
2020-11-11 18:04:39 gpg-agent[68355] ssh handler 0x700006334000 for fd 8 terminated
```

**Comment by rfpronk** [comment] 2020-11-11 17:31
I don't know why I haven't tried this before...
I created a ed25519 key file instead of using the Yubikey
```
ssh-keygen -o -a 256 -t ed25519
```

Using that key, it simply always works. So something isn't playing nice between this module, ssh agent forwarding and the Yubikey. Might be a firmware problem in the Yubikey. I will contact them about this.

**Comment by aswen** [comment] 2020-11-11 17:32
I created that [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969330). I would love to take advantage of the new Yubi with ED25519 keys so I will follow this issue :)

**Comment by jac-cbi** [comment] 2021-07-17 20:33
I’m experiencing the same issue.  My Yubikey 5C has the most recent firmware, and I’m seeing the same error message in /var/log/auth.log.  (Artix Linux aarch64 on rpi4B fwiw).  

I have also required touch for all actions on the yubikey.  I’ve never seen the light flash yet, but I just set it up today.  I’m also using ed25519 keys exclusively.  SSH and SSH via agent forwarding work fine.  Both require that I touch the Yubikey.

I see the Debian bug report didn’t generate any solutions yet.  If ssh works with a forwarded Yubikey, I’m inclined to think that pam_ssh_agent_auth.so is the one at fault here.

**Comment by KunoiSayami** [comment] 2021-10-17 17:15
Same here, pam log output:
```
Oct 18 01:04:07 sudo[25629]: pam_ssh_agent_auth: matching key found: file/command /home/114514/.ssh/authorized_keys, line 6
Oct 18 01:04:07 sudo[25629]: pam_ssh_agent_auth: Found matching ED25519 key: f9:00:00:00:00:00:00:00:00:00:00:00:00:00:03:65
Oct 18 01:04:07 sudo[25629]: pam_ssh_agent_auth: Agent admitted failure to sign using the key.
```

**Comment by FlorianFranzen** [comment] 2021-10-20 18:23
I ran into the same issue on NixOS. A second RSA key on an older yubikey works flawlessly in the same setup.

After reading [gnupg#5041](https://dev.gnupg.org/T5041) I am worried this could be on the yubikey side. Has anyone tried reducing the size of the data passed to the yubikey to be signed? The standard does not limit the size of the data passed, yet most digital signatures probably use Ed25519ph.

**Comment by FlorianFranzen** [comment] 2021-10-20 19:18
I applied the following patch in a lazy attempt to reduces the size of the data being signed:
```diff
--- a/iterate_ssh_agent_keys.c
+++ b/iterate_ssh_agent_keys.c
@@ -188,7 +188,7 @@ pamsshagentauth_find_authorized_keys(const char * user, const char * ruser, cons
     uid_t uid = getpwnam(ruser)->pw_uid;
 
     OpenSSL_add_all_digests();
-    pamsshagentauth_session_id2_gen(&session_id2, user, ruser, servicename);
+    //pamsshagentauth_session_id2_gen(&session_id2, user, ruser, servicename);
 
     if ((ac = ssh_get_authentication_connection(uid))) {
         pamsshagentauth_verbose("Contacted ssh-agent of user %s (%u)", ruser, uid);
```
Now GnuPG consistently sends around 145 bytes to the yubikey to sign instead of previously often up to 800 bytes. As a result everything just works again, as it does with my 4k RSA keys.

Part of the session id the patch removes is a randomly sized cookie (16-255 bytes), which explains why the yubikey would sometimes still work. If you are lucky with a small cookie size and executing a short sudo command from a short path on a host with a short hostname the yubikey can handle the signature.

A patch in the spirit of the codebase would probably just limit the size of the cookie (currently up to 256 bytes) and maybe remove some of the fields. 

Personally I would get rid of everything and just send a fixed size of random bytes. Sending all this info to the agent who just blindly signs it will only ever serve as a information leak at best.

Anyhow, this puts the problem on the side of the Yubikey and I am in touch with Yubico about it.

**EDIT**: I wrote a more intelligent version that just send 1024 random bits as session id that I am currently using successfully on multiple production systems. It is available [here](https://github.com/FlorianFranzen/pam_ssh_agent_auth/commit/db2d41937e714b56d17771f8ee3d61f11c26cc7e).

It essentially generates the session id like this:
```c
    for (i = 0; i < 32; i++) {    
        pamsshagentauth_buffer_put_int(session_id2, pamsshagentauth_arc4random());
    }
```
(Yes, this is how the current codebase does it for cookies too. And I know about `arc4random_buf(...)`, but it might not be available on BSD.)

**Comment by KunoiSayami** [comment] 2021-10-21 18:51
Thx @FlorianFranzen's share, it works for me now.

**Comment by git-noise** [comment] 2022-02-01 14:42
@FlorianFranzen 
Oh many thanks for this one, it bothered me for a long time. Would you have any news on the Yubico discussion by any chance?

Best,

**Comment by bootc** [comment] 2022-02-02 23:32
This is actually fixed with GnuPG [2.3.4](https://lists.gnupg.org/pipermail/gnupg-announce/2021q4/000468.html) and [2.2.33](https://lists.gnupg.org/pipermail/gnupg-announce/2021q4/000467.html) - look at the changelog entry marked [T5682](https://dev.gnupg.org/T5682). You'll see the latter even links back here, though no mention of it was made here.

I can confirm that GnuPG 2.3.4 on my Mac via Homebrew does indeed fix this issue for me.

**Closed** 2022-02-03 11:36 UTC

**Comment by sebastianrasor** [comment] 2025-03-11 08:30
I am experiencing this issue on `gpg (GnuPG) 2.4.7`

**Comment by TLATER** [comment] 2025-10-20 17:31
Same here, I get these messages on the server:

```
Oct 20 14:57:24 hetzner-1 sudo[7642]: pam_ssh_agent_auth: matching key found: file/command /etc/ssh/authorized_keys.d/tlater, line 4
Oct 20 14:57:24 hetzner-1 sudo[7642]: pam_ssh_agent_auth: Found matching ED25519 key: 9f:40:a8:30:5a:4d:9b:63:87:07:fa:e7:d2:02:b2:4a
Oct 20 14:57:24 hetzner-1 sudo[7642]: pam_ssh_agent_auth: Agent admitted failure to sign using the key.
Oct 20 14:57:24 hetzner-1 sudo[7642]: pam_ssh_agent_auth: Failed Authentication: `tlater' as `tlater' using /etc/ssh/authorized_keys.d/%u
Oct 20 14:57:24 hetzner-1 sudo[7642]: pam_unix(sudo:auth): conversation failed
Oct 20 14:57:24 hetzner-1 sudo[7642]: pam_unix(sudo:auth): auth could not identify password for [tlater]
```

and these messages in the ssh agent:

```
Oct 20 21:57:21 yui gpg-agent[551018]: scdaemon[551018]: detected reader 'Yubico YubiKey FIDO+CCID 00 00'
Oct 20 21:57:21 yui gpg-agent[551018]: scdaemon[551018]: detected reader 'Yubico YubiKey FIDO+CCID 00 00'
Oct 20 21:57:22 yui gpg-agent[551018]: scdaemon[551018]: detected reader 'Yubico YubiKey FIDO+CCID 00 00'
Oct 20 21:57:22 yui gpg-agent[26665]: smartcard signing failed: General error
Oct 20 21:57:22 yui gpg-agent[26665]: ssh sign request failed: General error <GPG Agent>
Oct 20 21:57:22 yui gpg-agent[551018]: scdaemon[551018]: detected reader 'Yubico YubiKey FIDO+CCID 00 00'
Oct 20 21:57:24 yui gpg-agent[551018]: scdaemon[551018]: detected reader 'Yubico YubiKey FIDO+CCID 00 00'
Oct 20 21:57:24 yui gpg-agent[551018]: scdaemon[551018]: detected reader 'Yubico YubiKey FIDO+CCID 00 00'
Oct 20 21:57:24 yui gpg-agent[26665]: smartcard signing failed: General error
Oct 20 21:57:24 yui gpg-agent[26665]: ssh sign request failed: General error <GPG Agent>
```

Curiously, the issue appears to be somewhat flaky; repeating the `sudo` sometimes makes it just work, and once it does of course the auth is cached. This doesn't help all that much with scripts, though.

Edit to not spam the thread: Yep, after switching to another module it works again, personally I picked [pam_rssh](https://github.com/z4yx/pam_rssh) because it was simply more easily accessible.

**Comment by pallaswept** [comment] 2025-10-20 17:41
FYI, this exists now: https://github.com/nresare/pam-ssh-agent

I'm not using a yubikey so I'm not sure, but 've been using it as a drop in replacement for this project+several critical PRs that have not been merged, it's working great, and actively maintained. Maybe it will help you, too?

Edit: I hope it's OK to link to another project here, I don't mean to step on any toes, just, this project appears to have been dead for some time, with many important PRs un-merged and no commits in several years. I just wanted to help people out who rely on it.

**Comment by FlorianFranzen** [comment] 2026-03-15 09:33
Same here, the issue reappeared with a new GnuPG releases last year. For now I just switched to one of the alternatives mentioned in this thread.

Already invested to much time into this while the maintainer @jbeverly seems to have abandoned this project anyway.
